# Generated by Django 3.2.13 on 2022-06-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'contact_emails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'contact_phones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'contact_types',
                'managed': False,
            },
        ),
    ]
